// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yairwymymtcbuypwnfmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhaXJ3eW15bXRjYnV5cHduZm1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ2NDk1NzAsImV4cCI6MjEwMDIyNTU3MH0.6hjnByaVSQjvQClnOkIz8BEu5m8OUJXjTBsX0mML94M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});